Feature property search
Ludogorie-Soft/villagelife-front-end pull request #96
Opened 2024-11-27 20:22 UTC by TodorYanakiev

2024-11-27 21:02 UTC, atche1 commented on src/main/resources/static/js/navMenuProperties.js
> +// Extract the current page from the URL path
remove unnecessary comments

2024-11-27 21:11 UTC, Nadezhda358 requested changes

2024-11-27 21:11 UTC, Nadezhda358 commented on src/main/resources/messages_bg.properties
> +advanced.property.search.types.agricultural.land=Земеделска земя
You can use the existing translations of the PropertyType enum

2024-11-28 21:03 UTC, Nadezhda358 approved these changes

2024-11-30 19:49 UTC, merged